name: asana

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - review_requested

# to avoid creating duplicate tasks.
concurrency: ci-${{ github.ref }}

jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - uses: keitap/github-asana-request-review-action@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          ASANA_TOKEN: "${{ secrets.ASANA_TOKEN }}"